### ISSUE TITLE
See pulses on all TPs, but screen doesn't update counts

### ISSUE THREAD

**Issue by hswhhe-uiuc** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#122]
Hi, I have a question about the Arduino/screen readouts. I looked at the BNC signal and all the test points on my detector, and I can see reasonable signals from the Oscilloscope. However, the screen counts doesn't update at all, except one fake count at the beginning. I tried to lower the signal threshold from Arduino but it doesn't change anything. Do you have any suggestions? The pictures below are the signal from BNC&TP2, BNC&TP3, and my main board. Thank you so much!

![9AB64355-5C04-483D-8A6B-BE673DAD9D1C](https://github.com/user-attachments/assets/2f8e71cb-c0a5-4e78-98f9-391d7663e8f5)
![5F0E57A0-F5B3-4E80-8297-E2DC39FB6280](https://github.com/user-attachments/assets/94aca771-8dc7-4b9f-ba15-a1d14e0a63ad)
![06921035-872C-49A8-A293-664949AD29A9](https://github.com/user-attachments/assets/134fdcd8-4d97-42ec-b440-4e1332c4425e)
![1A6F5807-520C-4750-A6E7-866DDE2F4C0A](https://github.com/user-attachments/assets/6eed21cd-15d4-406f-b99e-2eee79e12836)

**Comment by spenceraxani** [comment]
Hi,

I would recommend changing the trigger threshold back to its original value. I think your issue is simply the solder connection on the Arduino. I can see several suspect connections. I would also solder all the pins.

Best,

Spencer

─
Dr. Spencer N. Axani
***@***.*** ***@***.***> 

Assistant Professor
The University of Delaware
203 Sharp Lab
104 The Green, Newark, DE 19716
(608) 572-8426

**Comment by hswhhe-uiuc** [comment]
Hi Spencer,

Thank you so much! It worked after more soldering on Arduino.
