### ISSUE TITLE
Schematic R4

### ISSUE THREAD

**Issue by Phoenix1747** [spenceraxani/CosmicWatch-Desktop-Muon-Detector-v2#57]
Hi, what exactly is R4 doing just before the pre-amp? Do you use it to minimize the input bias current?

**Comment by spenceraxani** [comment]
Hi,

It’s actually for isolating the trace capacitance on the input to the op amp. Although, it’s not really doing its job perfectly, since I should have mounted it as close as possible to the pin on the op amp. 

The value isn’t particularly important for this one, but I would recommend between 50 and 1k Ohms.

Thanks,

Spencer

**Comment by Phoenix1747** [comment]
Ah I see, thanks!
